[tool.poetry]
name = "async-kafka-producer"
version = "0.1.0"
description = ""
authors = ["Vladimir Olokhtonov"]

[tool.poetry.dependencies]
python = "^3.9.0"
confluent-kafka = "2.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

